
const Discord = require("discord.js");

const CustomFunctions = require("../functions/funcs.js");

module.exports.run = async (bot, message, szArgs) =>
{
	const user = message.author;

	if(CustomFunctions.isEmpty(szArgs[0]))
	{
		return await message.reply(" :no_entry: this Google search query can't be empty you scrub :facepalm: ! Type **!lmgtfy** ``<your text here>`` :no_entry:");
	}

	if(message.mentions.members.first())
	{
		return await message.reply(" :no_entry: please don't mention people in your search query! :no_entry:");
	}

	let GoogleSearchQuery = szArgs.slice(0).join(' ').trim();

	const embed = new Discord.RichEmbed()
	.setAuthor("Cookie Monsta | Let Me Google That For You!", (bot.user.avatarURL === null) ? bot.user.defaultAvatarURL : bot.user.avatarURL)
	.setDescription(`Here, you pleb :point_right: [SEARCH](https://lmgtfy.com/?s=g&q=${encodeURIComponent(GoogleSearchQuery)})`)
	.setColor("#ADD8E6")
	.setThumbnail("https://i.imgur.com/N7iXYJ2.png")
	.setFooter("Generated by: @" + user.username, (user.avatarURL === null) ? user.defaultAvatarURL : user.avatarURL)

	await message.channel.send({embed});
};

module.exports.help =
{
    name: "lmgtfy"
};
