const Discord = require("discord.js");

const iBotPermissions =
[
    "MANAGE_ROLES", "MANAGE_CHANNELS", "KICK_MEMBERS", "BAN_MEMBERS", "CREATE_INSTANT_INVITE", "MANAGE_EMOJIS",
    "VIEW_CHANNEL", "SEND_MESSAGES", "SEND_TTS_MESSAGES", "MANAGE_MESSAGES", "EMBED_LINKS", "ATTACH_FILES", "READ_MESSAGE_HISTORY",
    "MENTION_EVERYONE", "ADD_REACTIONS", "USE_EXTERNAL_EMOJIS", "CONNECT", "SPEAK", "USE_VAD"
];

module.exports.run = async (bot, message, args) =>
{
    const user = message.author;
    const szGeneratedInvite = await bot.generateInvite(iBotPermissions).catch(console.error);

    const DiscordRichEmbed = new Discord.MessageEmbed()
    .setAuthor("Cookie Monsta | Invite Generator", bot.user.displayAvatarURL())
    .setColor(2003199)
    .setDescription("\n\n\n\n:link:  [Click Here!](" + szGeneratedInvite + ") to invite me to your Discord server!  :link:")
    .setThumbnail(bot.user.displayAvatarURL())
    .setFooter("Generated by: @" + user.username, user.displayAvatarURL())
    .setTimestamp();

    message.channel.send({ embed: DiscordRichEmbed });
};

module.exports.help =
{
    name: "invite"
};