const Discord = require("discord.js");

module.exports.run = async (bot, message, args) =>
{
    const user = message.author;
    const szGeneratedInvite = await bot.generateInvite("ADMINISTRATOR").catch(console.error);

    const DiscordRichEmbed = new Discord.MessageEmbed()
    .setAuthor("Cookie Monsta | Invite Generator", bot.user.displayAvatarURL())
    .setColor(2003199)
    .setDescription("\n\n\n\n:link:  [Click Here!](" + szGeneratedInvite + ") to invite me to your Discord server!  :link:")
    .setThumbnail(bot.user.displayAvatarURL())
    .setFooter("Generated by: @" + user.username, user.displayAvatarURL())
    .setTimestamp();

    message.channel.send({ embed: DiscordRichEmbed });
};

module.exports.help =
{
    name: "invite"
};